version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    env_file:
      - .env
    volumes:
      - ./app:/app/app 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge